# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True)),
            ],
        ),
    ]
