# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0003_remove_form_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='userid',
            field=models.IntegerField(null=True),
        ),
    ]
