# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0006_auto_20170719_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='userid',
            field=models.IntegerField(blank=True, null=True, verbose_name='id'),
        ),
    ]
