# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0007_auto_20170719_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Post',
        ),
    ]
