# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0009_auto_20170720_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='List',
        ),
    ]
