# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0010_auto_20170720_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
