# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0011_auto_20170721_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='id',
        ),
        migrations.AlterField(
            model_name='list',
            name='nombre',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
